MediaTurma/Models/Alunos.cs
using MediaTurma.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Globalization;

namespace MediaTurma.Models
{
    public class Alunos
    {
        private AlunosRepositorio notas;
        public string NomeAluno { get; set; }
        public int TotalDeAulas { get; set; }
        public double FaltasPermitidas { get; set; }
        public double Nota1 { get; set; }
        public double Nota2 { get; set; }
        public double Nota3 { get; set; }
        public double Nota4 { get; set; }
        public string TotalMedia { get; set; }
        public int Faltas { get; set; }

        public double MediaAlunos { 
        get{
              return (Nota1 + Nota2 + Nota3 + Nota4) / 4;

            }

        }
       

        

         public string Status
        {
            get
            {
                
                TotalDeAulas = 50;
                FaltasPermitidas = TotalDeAulas * 0.25;

                if (Faltas >= FaltasPermitidas && MediaAlunos <= 7.0)
                {
                    return "REPROVADO";
                }
                else
                {
                    return "APROVADO";
                }

            }
            set { }
         }

        public string StatusCurso
        {
            get
            {
                if (Faltas <= 50 && MediaAlunos <= 0.0)
                {
                    return "DESISTENTE";
                }
                else
                {
                    return "CURSANDO";
                }
            }
            set { }
        }

        public Alunos(string nomeAluno, double nota1, double nota2, double nota3, double nota4, int faltas)
        {
            

            NomeAluno = nomeAluno;
            Nota1 = nota1;
            Nota2 = nota2;
            Nota3 = nota3;
            Nota4 = nota4;
            
            Faltas = faltas;

                        

        }

        public List<Alunos> RetornarAlunos()
        {
            return notas.SelecionarTodos();
        }

        public Alunos()
        {
            notas = new AlunosRepositorio();
         
        }

        public Alunos BuscarAluno(string nomeAluno)
        {
            return notas.BuscarAluno(nomeAluno);
        }

        public void IncluirAluno(Alunos alunos)
        {
            notas.IncluirAluno(alunos);
        }

        public void EditarNota(Alunos alunos)
        {
            notas.EditarNota(alunos);
        }

        public void ExcluirNota(string nomeAluno)
        {
            notas.ExcluirAluno(nomeAluno);
        }

    }

}

MediaTurma/Models/ErrorViewModel.cs
using System;

namespace MediaTurma.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MediaTurma/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediaTurma.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MediaTurma.Controllers
{
    public class AlunosController : Controller

    {
        Alunos alunos;
        public AlunosController()
        {
            alunos = new Alunos();
        }
    
       // GET: Alunos
        public ActionResult Index()
        {
            return View(alunos.RetornarAlunos() ?? new List<Alunos>());
        }

        // GET: Alunos/Details/5
        public ActionResult Details(string nomeAluno)
        {
            
            return View(alunos.BuscarAluno(nomeAluno) ?? new Alunos());
        }

        // GET: Alunos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Alunos aluno)
        {
            try
            {
                // TODO: Add insert logic here
                alunos.IncluirAluno(aluno);
                return View("index", alunos.RetornarAlunos());
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Alunos/Edit/5
        public ActionResult Edit(string nomeAluno)
        {
            return View(alunos.BuscarAluno(nomeAluno) ?? new Alunos());
        }

        // POST: Alunos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Alunos alunos)
        {
            try
            {
                // TODO: Add update logic here
                alunos.EditarNota(alunos);
                return View("index", alunos.RetornarAlunos());
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Alunos/Delete/5
        public ActionResult Delete(string nomeAluno)
        {
            alunos.ExcluirNota(nomeAluno);
            return View("index", alunos.RetornarAlunos());
        }

      
        
    }
}

MediaTurma/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MediaTurma.Models;

namespace MediaTurma.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MediaTurma/Views/Alunos/Create.cshtml
@model MediaTurma.Models.Alunos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Alunos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeAluno" class="control-label"></label>
                <input asp-for="NomeAluno" class="form-control" />
                <span asp-validation-for="NomeAluno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota1" class="control-label "></label>
                <input asp-for="Nota1" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota2" class="control-label"></label>
                <input asp-for="Nota2" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota3" class="control-label"></label>
                <input asp-for="Nota3" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota4" class="control-label"></label>
                <input asp-for="Nota4" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faltas" class="control-label"></label>
                <input asp-for="Faltas" class="form-control" />
                <span asp-validation-for="Faltas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MediaTurma/Views/Alunos/Details.cshtml
@model MediaTurma.Models.Alunos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Alunos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeAluno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeAluno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota4)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota4)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusCurso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusCurso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MediaAlunos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MediaAlunos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Faltas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Faltas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MediaTurma/Views/Alunos/Edit.cshtml
@model MediaTurma.Models.Alunos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Alunos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeAluno" class="control-label"></label>
                <input asp-for="NomeAluno" class="form-control" />
                <span asp-validation-for="NomeAluno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota1" class="control-label"></label>
                <input asp-for="Nota1" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota2" class="control-label"></label>
                <input asp-for="Nota2" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota3" class="control-label"></label>
                <input asp-for="Nota3" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nota4" class="control-label"></label>
                <input asp-for="Nota4" class="form-control input-validation-error" data-val="false" />
                <span asp-validation-for="Nota4" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Faltas" class="control-label"></label>
                <input asp-for="Faltas" class="form-control" />
                <span asp-validation-for="Faltas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MediaTurma/Views/Alunos/Index.cshtml
@model IEnumerable<MediaTurma.Models.Alunos>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.NomeAluno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MediaAlunos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Faltas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusCurso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.NomeAluno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nota4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MediaAlunos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faltas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusCurso)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { nomeAluno = item.NomeAluno }) |
                @Html.ActionLink("Details", "Details", new { nomeAluno=item.NomeAluno }) |
                @Html.ActionLink("Delete", "Delete", new { nomeAluno=item.NomeAluno })
            </td>
        </tr>
}
    </tbody>
</table>

MediaTurma/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MediaTurma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediaTurma</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MediaTurma</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MediaTurma - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>